on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
          - runner: ubuntu-24.04-arm
          - runner: macos-13
          - runner: macos-latest
          - runner: windows-latest
          - runner: windows-11-arm

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist
          sccache: 'true'
      - run: python -mpip install pytest
      - run: python -mpip install --find-links dist testurin
      - run: python -mpytest tests/
