on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
          - runner: ubuntu-24.04-arm
          - runner: macos-13
          - runner: macos-latest
          - runner: windows-latest
          - runner: windows-11-arm

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: python -mpip install tox
      - run: python -m tox
